Repository HIGHFIVE-SW/user-service, pull requests merged in 2025-06, with the labels that each got.

#22 feat: exp update api 기능 구현
  src/main/java/com/trendist/user_service/domain/user/controller/UserController.java
  src/main/java/com/trendist/user_service/domain/user/dto/response/UserUpdateExpResponse.java
  src/main/java/com/trendist/user_service/domain/user/service/RankingScheduler.java
  src/main/java/com/trendist/user_service/domain/user/service/UserService.java
  src/main/java/com/trendist/user_service/global/config/SecurityConfig.java
Labels: feat

#24 chore: 쿠버네티스 환경 구축
  src/main/java/com/trendist/user_service/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: refactor, chore

#26 chore: ci/cd 구축
  .github/workflows/cd-prod.yaml
  .github/workflows/ci.yaml
Labels: chore

#28 bug: cd 실패 해결을 위한 .kube 디렉토리 생성 추가
  .github/workflows/cd-prod.yaml
Labels: bug
